django/fourth_project/fourth_application/urls.py
from django.urls import path, re_path, include
from . import views


#template tagging
app_name = 'basic_app'

urlpatterns = [
    re_path(r'^relative/$', views.relative,name='relative'),
    re_path(r'^other/$', views.other,name='other'),
]

django/fourth_project/fourth_project/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from fourth_application import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.index,name='index'),
    re_path(r'^fourth_application/', include('fourth_application.urls')),
]

django/fourth_project/fourth_application/models.py
from django.db import models

# Create your models here.

django/fourth_project/fourth_application/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world', 'number':100}
    return render(request, 'fourth_application/index.html', context_dict)

def other(request):
    return render(request, 'fourth_application/other.html')

def relative(request):
    return render(request, 'fourth_application/relative_url_templates.html')

django/fourth_project/templates/fourth_application/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>base</title>
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
			crossorigin="anonymous"
		/>
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-light">
			<div class="container">
				<ul class="navbar-nav">
					<li><a class="navbar-brand" href="{% url "index" %}">BRAND</a></li>
					<li><a class="nav-link" href="{% url "admin:index" %}">Admin</a></li>
					<li><a class="nav-link" href="{% url "basic_app:other" %}">Other</a></li>
				</ul>
			</div>
		</nav>
		<div class="container">
			{% block body_block %}
			<h1>Hi this is base.html</h1>
			{% endblock body_block %}
		</div>
	</body>
</html>

django/fourth_project/templates/fourth_application/index.html
<!DOCTYPE html>
{% extends "fourth_application/base.html" %} {% block body_block %}
<h1>Hi this is index page</h1>
<h2>{{text|upper}}</h2>
<h2>{{text|cut:'hello'}}</h2>
<h2>{{number|add:"99"}}</h2>
{% endblock body_block %}

django/fourth_project/templates/fourth_application/other.html
<!DOCTYPE html>
{% extends "fourth_application/base.html" %}
{% block body_block %}
<h1>Hi this is other page</h1>
{% endblock body_block %}

django/fourth_project/templates/fourth_application/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>relative url html</title>
</head>
<body>
    
    <h1>Welcome to relative url templates</h1>
    <a href="{% url "basic_app:other" %}">other page</a>
    <a href="{% url "admin:index" %}">Link to Admin</a>
    <a href="{% url "index" %}">Link to Index</a>
</body>
</html>